TRELLO_API_KEY=''
TRELLO_API_SECRET=''
TRELLO_OAUTH_TOKEN=''

TRELLO_ORGANIZATION_ID = ''

CURRENT_STORY_BOARD = ''
CURRENT_EPIC_BOARD = ''
FUTURE_STORY_BOARD = ''
TRELLO_DB_CONNECTION_STRING = 'sqlite:///trello.db'
